/**
 * Data for Bhutan's administrative divisions
 * Dzongkhags (districts) and their Gewogs (blocks/sub-districts)
 * Including names in both English and Dzongkha script
 */

const bhutanRegions = [
  {
    dzongkhag: "Bumthang",
    dzongkhagDzongkha: "བུམ་ཐང་",
    gewogs: [
      { name: "Chhume", dzongkha: "ཆུ་སྨད་" },
      { name: "Chhoekhor", dzongkha: "ཆོས་འཁོར་" },
      { name: "Tang", dzongkha: "སྟང་" },
      { name: "Ura", dzongkha: "ཨུ་ར་" },
    ],
  },
  {
    dzongkhag: "Chhukha",
    dzongkhagDzongkha: "ཆུ་ཁ་",
    gewogs: [
      { name: "Bongo", dzongkha: "བོང་སྒོ་" },
      { name: "Chapcha", dzongkha: "ཆབ་ཆ་" },
      { name: "Darla", dzongkha: "དར་ལ་" },
      { name: "Geling", dzongkha: "དགེ་གླིང་" },
      { name: "Logchina", dzongkha: "ལོག་ཅིན་" },
      { name: "Metshina", dzongkha: "མེད་ཅིན་" },
      { name: "Phuntsholing", dzongkha: "ཕུན་ཚོགས་གླིང་" },
      { name: "Sampheling", dzongkha: "བསམ་ཕུ་གླིང་" },
      { name: "Bjachho", dzongkha: "བྱག་ཆོས་" },
      { name: "Dungna", dzongkha: "དུང་ན་" },
      { name: "Getena", dzongkha: "དགེ་བསྟན་ན་" },
    ],
  },
  {
    dzongkhag: "Dagana",
    dzongkhagDzongkha: "དར་དཀར་ན་",
    gewogs: [
      { name: "Dorona", dzongkha: "རྡོ་རོ་ན་" },
      { name: "Gesarling", dzongkha: "གེ་སར་གླིང་" },
      { name: "Gozhi", dzongkha: "སྒོ་ཞི་" },
      { name: "Kana", dzongkha: "ཀ་ན་" },
      { name: "Karmaling", dzongkha: "ཀརྨ་གླིང་" },
      { name: "Khebisa", dzongkha: "ཁེ་བི་ས་" },
      { name: "Lajab", dzongkha: "ལ་འཇབ་" },
      { name: "Nichula", dzongkha: "ནི་ཆུ་ལ་" },
      { name: "Tseza", dzongkha: "རྩེས་གཟར་" },
      { name: "Tsangkha", dzongkha: "ཚ་འཁར་" },
      { name: "Deorali", dzongkha: "དེའོ་ར་ལི་" },
    ],
  },
  {
    dzongkhag: "Gasa",
    dzongkhagDzongkha: "མགར་ས་",
    gewogs: [
      { name: "Khatoed", dzongkha: "མཁར་སྟོད་" },
      { name: "Khamae", dzongkha: "མཁར་སྨད་" },
      { name: "Laya", dzongkha: "ལ་ཡག་" },
      { name: "Lunana", dzongkha: "ལུང་ནག་ན་" },
    ],
  },
  {
    dzongkhag: "Haa",
    dzongkhagDzongkha: "ཧད་",
    gewogs: [
      { name: "Bji", dzongkha: "སྦྱིས་" },
      { name: "Eusu", dzongkha: "ཨེའུ་སུ་" },
      { name: "Katsho", dzongkha: "ཀ་ཚོ་" },
      { name: "Sama", dzongkha: "ས་མང་" },
      { name: "Sangbaykha", dzongkha: "སངས་སྦྱིས་ཁ་" },
      { name: "Gakiling", dzongkha: "དགའ་སྐྱིད་གླིང་" },
    ],
  },
  {
    dzongkhag: "Lhuentse",
    dzongkhagDzongkha: "ལྷུན་རྩེ་",
    gewogs: [
      { name: "Gangzur", dzongkha: "སྒང་ཟུར་" },
      { name: "Jarey", dzongkha: "བྱ་རེས་" },
      { name: "Khoma", dzongkha: "ཁོ་མ་" },
      { name: "Kurtoe", dzongkha: "ཀུར་སྟོད་" },
      { name: "Menbi", dzongkha: "མེན་བི་" },
      { name: "Metsho", dzongkha: "མེ་མཚོ་" },
      { name: "Tsenkhar", dzongkha: "བཙན་མཁར་" },
      { name: "Maenbi", dzongkha: "སྨན་སྦྱིས་" },
    ],
  },
  {
    dzongkhag: "Mongar",
    dzongkhagDzongkha: "མོང་སྒར་",
    gewogs: [
      { name: "Balam", dzongkha: "བ་ལམ་" },
      { name: "Chaskhar", dzongkha: "བྱ་སྐར་" },
      { name: "Drametse", dzongkha: "འབྲས་མེ་རྩེ་" },
      { name: "Drepung", dzongkha: "འབྲས་སྤུངས་" },
      { name: "Gongdue", dzongkha: "དགོངས་འདུས་" },
      { name: "Jurmey", dzongkha: "བྱུར་མེད་" },
      { name: "Kengkhar", dzongkha: "སྐེང་ཁར་" },
      { name: "Mongar", dzongkha: "མོང་སྒར་" },
      { name: "Narang", dzongkha: "ན་རང་" },
      { name: "Ngatshang", dzongkha: "རྔ་ཚང་" },
      { name: "Saleng", dzongkha: "ས་གླིང་" },
      { name: "Serthi", dzongkha: "གསེར་ཐིག་" },
      { name: "Silambi", dzongkha: "སི་ལམ་བི་" },
      { name: "Thangrong", dzongkha: "ཐང་རོང་" },
      { name: "Tsamang", dzongkha: "ཚ་མང་" },
      { name: "Tsakaling", dzongkha: "ཚ་ཀ་གླིང་" },
      { name: "Sherimung", dzongkha: "ཤེ་རི་མུང་" },
    ],
  },
  {
    dzongkhag: "Paro",
    dzongkhagDzongkha: "སྤ་རོ་",
    gewogs: [
      { name: "Doga", dzongkha: "དོ་དགའ་" },
      { name: "Doteng", dzongkha: "མདོ་སྟེང་" },
      { name: "Hungrel", dzongkha: "ཧུང་རལ་" },
      { name: "Lamgong", dzongkha: "ལམ་སྒང་" },
      { name: "Lungnyi", dzongkha: "ལུང་གཉིས་" },
      { name: "Naja", dzongkha: "ན་བྱ་" },
      { name: "Shaba", dzongkha: "ཤ་བ་" },
      { name: "Tsento", dzongkha: "བཙན་ཏོག་" },
      { name: "Wangchang", dzongkha: "དབང་ཆང་" },
      { name: "Soe", dzongkha: "སོས་" },
    ],
  },
  {
    dzongkhag: "Pemagatshel",
    dzongkhagDzongkha: "པད་མ་དགའ་ཚལ་",
    gewogs: [
      { name: "Chimung", dzongkha: "སྤྱི་མུང་" },
      { name: "Choekhorling", dzongkha: "ཆོས་འཁོར་གླིང་" },
      { name: "Chongshing", dzongkha: "ཅོང་ཤིང་" },
      { name: "Dechenling", dzongkha: "བདེ་ཆེན་གླིང་" },
      { name: "Dungmin", dzongkha: "དུང་མིན་" },
      { name: "Khar", dzongkha: "མཁར་" },
      { name: "Nanong", dzongkha: "ན་ནོང་" },
      { name: "Shumar", dzongkha: "ཤུ་མར་" },
      { name: "Yurung", dzongkha: "གཡུ་རུང་" },
      { name: "Zobel", dzongkha: "ཟོ་བེལ་" },
      { name: "Norbugang", dzongkha: "ནོར་བུ་སྒང་" },
    ],
  },
  {
    dzongkhag: "Punakha",
    dzongkhagDzongkha: "སྤུ་ན་ཁ་",
    gewogs: [
      { name: "Chhubu", dzongkha: "ཆུ་བུ་" },
      { name: "Dzomi", dzongkha: "རྫོ་མི་" },
      { name: "Goenshari", dzongkha: "དགོན་ཤར་རི་" },
      { name: "Kabjisa", dzongkha: "སྐར་སྦྱིས་ས་" },
      { name: "Lingmukha", dzongkha: "གླིང་མུ་ཁ་" },
      { name: "Shenga Bjimi", dzongkha: "ཤིང་ང་སྦྱིས་མི་" },
      { name: "Talo", dzongkha: "རྟ་ལོག་" },
      { name: "Toepisa", dzongkha: "སྟོད་པི་ས་" },
      { name: "Toewang", dzongkha: "སྟོད་དབང་" },
      { name: "Guma", dzongkha: "དགུ་མ་" },
    ],
  },
  {
    dzongkhag: "Samdrup Jongkhar",
    dzongkhagDzongkha: "བསམ་གྲུབ་ལྗོངས་མཁར་",
    gewogs: [
      { name: "Dewathang", dzongkha: "སྡེ་བ་ཐང་" },
      { name: "Gomdar", dzongkha: "སྒོམ་དར་" },
      { name: "Langchenphu", dzongkha: "གླང་ཆེན་ཕུག་" },
      { name: "Lauri", dzongkha: "ལ་ཝུ་རི་" },
      { name: "Martshala", dzongkha: "སྨར་ཚ་ལ་" },
      { name: "Orong", dzongkha: "ཨོ་རོང་" },
      { name: "Pemathang", dzongkha: "པད་མ་ཐང་" },
      { name: "Phuntshothang", dzongkha: "ཕུན་ཚོགས་ཐང་" },
      { name: "Samrang", dzongkha: "བསམ་རང་" },
      { name: "Serthi", dzongkha: "གསེར་ཐིག་" },
      { name: "Wangphu", dzongkha: "དབང་ཕུག་" },
    ],
  },
  {
    dzongkhag: "Samtse",
    dzongkhagDzongkha: "བསམ་རྩེ་",
    gewogs: [
      { name: "Bara", dzongkha: "བྱ་ར་" },
      { name: "Biru", dzongkha: "བི་རུ་" },
      { name: "Chargharay", dzongkha: "ཆར་འཁྱར་རེ་" },
      { name: "Denchukha", dzongkha: "གདན་ཆུ་ཁ་" },
      { name: "Dophuchen", dzongkha: "རྡོ་ཕུ་ཆེན་" },
      { name: "Dungtoe", dzongkha: "དུང་སྟོད་" },
      { name: "Gomtu", dzongkha: "སྒོམ་སྟུག་" },
      { name: "Lahireni", dzongkha: "ལ་ཧི་རེ་ནི་" },
      { name: "Lehereni", dzongkha: "ལེ་ཧེ་རེ་ནི་" },
      { name: "Namgyelcholing", dzongkha: "རྣམ་རྒྱལ་ཆོས་གླིང་" },
      { name: "Norgaygang", dzongkha: "ནོར་དགའ་སྒང་" },
      { name: "Pagli", dzongkha: "པ་གླི་" },
      { name: "Samtse", dzongkha: "བསམ་རྩེ་" },
      { name: "Sangacholing", dzongkha: "སངས་རྒྱས་ཆོས་གླིང་" },
      { name: "Sipsu", dzongkha: "སྲིབ་སུ་" },
      { name: "Tading", dzongkha: "རྟ་དིང་" },
      { name: "Tendruk", dzongkha: "སྟེང་འབྲུག་" },
      { name: "Ugentse", dzongkha: "ཨོ་རྒྱན་རྩེ་" },
      { name: "Yoeseltse", dzongkha: "ཡོན་སེལ་རྩེ་" },
    ],
  },
  {
    dzongkhag: "Sarpang",
    dzongkhagDzongkha: "གསར་སྤང་",
    gewogs: [
      { name: "Bhur", dzongkha: "བུར་" },
      { name: "Chhuzagang", dzongkha: "ཆུ་བཟང་སྒང་" },
      { name: "Dekiling", dzongkha: "བདེ་སྐྱིད་གླིང་" },
      { name: "Gelephu", dzongkha: "དགེ་ལེགས་ཕུ་" },
      { name: "Jigmecholing", dzongkha: "འཇིགས་མེད་ཆོས་གླིང་" },
      { name: "Samtenling", dzongkha: "བསམ་གཏན་གླིང་" },
      { name: "Serzhong", dzongkha: "གསེར་ཞོང་" },
      { name: "Shompangkha", dzongkha: "ཤོམ་ཕང་ཁ་" },
      { name: "Tareythang", dzongkha: "ཏ་རས་ཐང་" },
      { name: "Umling", dzongkha: "ཨུམ་གླིང་" },
      { name: "Singye", dzongkha: "སེང་གེ་" },
      { name: "Gakidling", dzongkha: "དགའ་སྐྱིད་གླིང་" },
    ],
  },
  {
    dzongkhag: "Thimphu",
    dzongkhagDzongkha: "ཐིམ་ཕུག་",
    gewogs: [
      { name: "Chang", dzongkha: "ལྕང་" },
      { name: "Dagala", dzongkha: "དགའ་དགའ་ལ་" },
      { name: "Genye", dzongkha: "དགེ་སྙེ་" },
      { name: "Kawang", dzongkha: "ཀ་དབང་" },
      { name: "Lingzhi", dzongkha: "གླིང་བཞི་" },
      { name: "Mewang", dzongkha: "སྨད་དབང་" },
      { name: "Naro", dzongkha: "ན་རོ་" },
      { name: "Soe", dzongkha: "སོས་" },
    ],
  },
  {
    dzongkhag: "Trashigang",
    dzongkhagDzongkha: "བཀྲིས་སྒང་",
    gewogs: [
      { name: "Bartsham", dzongkha: "བར་མཚམས་" },
      { name: "Bidung", dzongkha: "བི་དུང་" },
      { name: "Kanglung", dzongkha: "རྐང་ལུང་" },
      { name: "Kangpara", dzongkha: "རྐང་པ་ར་" },
      { name: "Khaling", dzongkha: "ཁ་གླིང་" },
      { name: "Lumang", dzongkha: "ཀླུ་མང་" },
      { name: "Merak", dzongkha: "མེ་རག་" },
      { name: "Phongmey", dzongkha: "ཕོངས་མེད་" },
      { name: "Radhi", dzongkha: "ར་དྷི་" },
      { name: "Sakteng", dzongkha: "སག་སྟེང་" },
      { name: "Samkhar", dzongkha: "བསམ་མཁར་" },
      { name: "Shongphu", dzongkha: "ཤོང་ཕུག་" },
      { name: "Thrimshing", dzongkha: "ཁྲིམས་ཤིང་" },
      { name: "Uzorong", dzongkha: "ཨུ་ཟོ་རོང་" },
      { name: "Yangnyer", dzongkha: "ཡང་གཉེར་" },
    ],
  },
  {
    dzongkhag: "Trashiyangtse",
    dzongkhagDzongkha: "བཀྲིས་གཡང་རྩེ་",
    gewogs: [
      { name: "Bumdeling", dzongkha: "བུམ་སྡེ་གླིང་" },
      { name: "Jamkhar", dzongkha: "བྱམས་མཁར་" },
      { name: "Khamdang", dzongkha: "ཁམས་དང་" },
      { name: "Ramjar", dzongkha: "རམ་བྱར་" },
      { name: "Toetsho", dzongkha: "སྟོད་མཚོ་" },
      { name: "Yangtse", dzongkha: "གཡང་རྩེ་" },
      { name: "Tomzhangtshen", dzongkha: "སྟོམ་ཞང་ཚན་" },
      { name: "Yalang", dzongkha: "ཡ་ལང་" },
    ],
  },
  {
    dzongkhag: "Trongsa",
    dzongkhagDzongkha: "ཀྲོང་གསར་",
    gewogs: [
      { name: "Drakteng", dzongkha: "བྲག་སྟེང་" },
      { name: "Langthel", dzongkha: "གླང་མཐིལ་" },
      { name: "Nubi", dzongkha: "ནུབ་བི་" },
      { name: "Tangsibji", dzongkha: "ཐང་སི་བྱི་" },
      { name: "Korphu", dzongkha: "སྐོར་ཕུག་" },
    ],
  },
  {
    dzongkhag: "Tsirang",
    dzongkhagDzongkha: "རྩི་རང་",
    gewogs: [
      { name: "Barshong", dzongkha: "བར་གཤོང་" },
      { name: "Dunglagang", dzongkha: "དུང་ལ་སྒང་" },
      { name: "Goserling", dzongkha: "གོ་སེར་གླིང་" },
      { name: "Kikhorthang", dzongkha: "སྐྱིད་ཁོར་ཐང་" },
      { name: "Mendrelgang", dzongkha: "མན་དྲེལ་སྒང་" },
      { name: "Patshaling", dzongkha: "པད་ཚ་གླིང་" },
      { name: "Phuentenchu", dzongkha: "ཕུན་ཚོགས་ཆུ་" },
      { name: "Rangthangling", dzongkha: "རང་ཐང་གླིང་" },
      { name: "Semjong", dzongkha: "སེམས་ལྗོངས་" },
      { name: "Sergithang", dzongkha: "གསེར་གྱི་ཐང་" },
      { name: "Tsholingkhar", dzongkha: "མཚོ་གླིང་མཁར་" },
      { name: "Tsirangtoe", dzongkha: "རྩི་རང་སྟོད་" },
    ],
  },
  {
    dzongkhag: "Wangdue Phodrang",
    dzongkhagDzongkha: "དབང་འདུས་ཕོ་བྲང་",
    gewogs: [
      { name: "Athang", dzongkha: "ཨ་ཐང་" },
      { name: "Bjena", dzongkha: "སྦྱེ་ན་" },
      { name: "Daga", dzongkha: "དར་དཀར་" },
      { name: "Dangchu", dzongkha: "དངུལ་ཆུ་" },
      { name: "Gangte", dzongkha: "སྒང་སྟེ་" },
      { name: "Gasetsho Gom", dzongkha: "དགའ་སྡེ་ཚོ་གོང་མ་" },
      { name: "Gasetsho Wom", dzongkha: "དགའ་སྡེ་ཚོ་འོག་མ་" },
      { name: "Kazhi", dzongkha: "བཀའ་བཞི་" },
      { name: "Nahi", dzongkha: "ན་ཧི་" },
      { name: "Nyisho", dzongkha: "ཉི་ཤོད་" },
      { name: "Phangyul", dzongkha: "ཕངས་ཡུལ་" },
      { name: "Phobji", dzongkha: "ཕོབ་སྦྱིས་" },
      { name: "Ruepisa", dzongkha: "རུས་སྤི་ས་" },
      { name: "Sephu", dzongkha: "སྲས་ཕུག་" },
      { name: "Thedtsho", dzongkha: "ཐེད་ཚོ་" },
    ],
  },
  {
    dzongkhag: "Zhemgang",
    dzongkhagDzongkha: "གཞམས་སྒང་",
    gewogs: [
      { name: "Bardo", dzongkha: "བར་མདོ་" },
      { name: "Bjoka", dzongkha: "བྱོ་ཀ་" },
      { name: "Goshing", dzongkha: "གོ་ཞིང་" },
      { name: "Nangkor", dzongkha: "ནང་སྐོར་" },
      { name: "Ngangla", dzongkha: "ནང་ལ་" },
      { name: "Phangkhar", dzongkha: "ཕང་མཁར་" },
      { name: "Shingkhar", dzongkha: "ཤིང་མཁར་" },
      { name: "Trong", dzongkha: "ཁྲོང་" },
    ],
  },
];

module.exports = bhutanRegions;
